/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lailah.awtwork;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Fretty
 */
public class Addition_awt extends java.awt.Frame implements  ActionListener {

    /**
     * Creates new form Addition_awt
     */
    TextField t1;
    Label l1;
    TextField t2;
    Label l2;
    TextField t3;
    Label l3;
    int x,y,z;
    public Addition_awt() {
        initComponents();
        try{
        t1 = new TextField(8);
        l1 = new Label("Enter 1st number");
        t2 = new TextField(8);
        l2 = new Label("Enter 2nd number");
        t3 = new TextField(8);
        l3 = new Label("Result is ");
        Button b1 = new Button("Addition");
        t1.setBounds(140,30,100,20);
        l1.setBounds(30,30,200,20);
        t2.setBounds(400,30,100,20);
        l2.setBounds(290,30,200,20);
        t3.setBounds(230,70,100,20);
        l3.setBounds(170,70,200,20);
        b1.setBounds(200, 120, 90,30);
        b1.addActionListener(this);
        add(t1);add(l1);add(t2);add(l2);add(t3);add(l3);add(b1);
        t1.setText("0"); t2.setText("0");
        
       
        setLayout(null);
        setSize(700,400);
        setVisible(true);
        }catch(Exception ex){
            System.err.println(ex);
        }
    }
    public void actionPerformed(ActionEvent ae)
    {        
        String s1,s2, s;
        s1=t1.getText();
        x=Integer.parseInt(s1);
        s2=t2.getText();
        y=Integer.parseInt(s2);
         z=x+y;
          s=String.valueOf(z);
         t3.setText(s);
    }
     public boolean action(Event event, Object object){
          repaint(); //refresh
          return true;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addition_awt().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
