/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lailah.trialswork;
import java.awt.*; import java.awt.event.*; import javax.swing.*; 
/**
 *
 * @author Lailah
 */
public class SwingControlDemo1 extends javax.swing.JFrame {
  private JFrame mainFrame;    private JLabel headerLabel;    private JLabel statusLabel;    private JPanel controlPanel; 
    /**
     * Creates new form SwingControlDemo1
     */
    public SwingControlDemo1() {
        //initComponents();
         prepareGUI(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         SwingControlDemo1  swingControlDemo = new SwingControlDemo1();             
         swingControlDemo.showButtonDemo(); 
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingControlDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingControlDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingControlDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingControlDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingControlDemo1().setVisible(true);
            }
        });
    }
    
     private void prepareGUI(){      
         mainFrame = new JFrame("Java Swing Examples");
         mainFrame.setSize(400,400);       
         mainFrame.setLayout(new GridLayout(3, 1));      
         mainFrame.addWindowListener(new WindowAdapter() {         
             public void windowClosing(WindowEvent windowEvent){            
                 System.exit(0);          
             }               });          
         headerLabel = new JLabel("", JLabel.CENTER);              
         statusLabel = new JLabel("",JLabel.CENTER);     
 
      statusLabel.setSize(350,100); 
 
      controlPanel = new JPanel();       
      controlPanel.setLayout(new FlowLayout()); 
 
      mainFrame.add(headerLabel);      
      mainFrame.add(controlPanel);       
      mainFrame.add(statusLabel);       
      mainFrame.setVisible(true);      
     }         
     
     private static ImageIcon createImageIcon(String path,        String description) {       
         java.net.URL imgURL = SwingControlDemo.class.getResource(path);      
         if (imgURL != null) {          
             return new ImageIcon(imgURL, description);       
         } else {                      
             System.err.println("Couldn't find file: " + path);          
             return null;       
         } 
   }       
     
     private void showButtonDemo(){       
         headerLabel.setText("Control in action: Button");  
 
      //resources folder should be inside SWING folder.      
      ImageIcon icon = createImageIcon("java_icon.png","Java"); 
       JButton okButton = new JButton("OK");              
       JButton javaButton = new JButton("Submit", icon);       
       JButton cancelButton = new JButton("Cancel", icon);       
       cancelButton.setHorizontalTextPosition(SwingConstants.LEFT);    
 
      okButton.addActionListener(new ActionListener() {          
          public void actionPerformed(ActionEvent e) {             
              statusLabel.setText("Ok Button clicked.");          
          }                
      }); 
 
      javaButton.addActionListener(new ActionListener() {          
          public void actionPerformed(ActionEvent e) {             
              statusLabel.setText("Submit Button clicked.");          
          }       }); 
 
      cancelButton.addActionListener(new ActionListener() {          
          public void actionPerformed(ActionEvent e) {             
              statusLabel.setText("Cancel Button clicked.");          
          }       }); 
 
      controlPanel.add(okButton);       
      controlPanel.add(javaButton);       
      controlPanel.add(cancelButton);        
 
      mainFrame.setVisible(true);      }
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
