/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lailah.awtdemos;
import java.awt.*;

/**
 *
 * @author Fretty
 */
public class Demo1 extends java.awt.Frame {
    
    /**
     * Creates new form Demo1
     */
    public Demo1() //constructor wc initialises Components 
    {
        initComponents();
        Button b1 = new Button("Click ME");
         Button b2 = new Button("Sai pali");
        b1.setBounds(100,100,100,50); //setting button position cols row width height
         b2.setBounds(300,100,100,50);
        add(b1); //make button visible
        add(b2);
        setLayout(null); //no layout manager
        setSize(500,300); //width height
        setVisible(true); //setvisibility true from default of false
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo1().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
