/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lailah.awtdemos;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Fretty
 */
public class Demo2 extends java.awt.Frame implements ActionListener //interface is implemented
{

    /**
     * Creates new form Demo2
     */
     TextField t1; //declare t1 b4 the constructor
     Label l1;
    public Demo2() {
        initComponents();
       t1 = new TextField(25);
       l1 = new Label("Click to receive Greetings");
        Button b1 = new Button("Click me");
        t1.setBounds(150,100,170,30);
        l1.setBounds(10, 100, 170, 20);
        b1.setBounds(50,170,100,30);
        add(t1);
        add(l1);
        add(b1);
        b1.addActionListener(this); //interface is added to the button
        setLayout(null);
        setSize(400,400);
        setVisible(true);
    }
//activate event
    public void actionPerformed(ActionEvent ae) //class ActionEvent is activated when ActionListener Interface is impemented
    {
        t1.setText("Hello Lailah Grant");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo2().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
